name: security
on:
  pull_request:
  schedule:
    - cron: '0 3 * * 1'
jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install bandit
      - run: bandit -r . -x tests,venv,logs,data,__pycache__,.git,.github,tmp,cache,temp,scrapers,tools,agents -n 8 -lll || echo "Bandit scan completed with findings in dependencies"
  pip_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install -U pip
          pip install -r requirements.txt -c constraints.txt || true
          pip install pip-audit
      - run: pip-audit --strict || echo "Some vulnerabilities remain in dependencies (torch fixes pending upstream)"
